 development:
   adapter: mysql2
   encoding: utf8
   database: sku_development
   username: root
   password: root
   host: localhost

 test:
   adapter: mysql2
   encoding: utf8
   database: sku_test
   username: root
   password: root
   host: localhost

 production:
   adapter: mysql2
   database: sku_production
   username: prod